server:
  port: 8099
  
spring:
  application:
    name: student-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
logging:
  level:
    com.example.howtodoinjava: DEBUG