server:
  port: 9098

spring:
  application:
    name: school-service
    
eureka:
  registerWithEureka: false
  fetchRegistry: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    com.example.howtodoinjava: DEBUG